### PR TITLE
remove zend-expressive as it is not required

### PR DESCRIPTION
**Pull request by basz**

### CODE REVIEW

**Comment by prolic** [comment]
Travis failed

**Comment by basz** [comment]
time thing again, you have an easy suggestion to mock time?

**Comment by prolic** [comment]
What's the problem exactly?

**Comment by basz** [comment]
new DateTime != new DateTime 6ms later... Therefore time comparisons fail sometimes.

**Comment by prolic** [comment]
I used often something like this:

```
$dateTime = new DateTimeImmutable('now');
$dateTime = $dateTime->modify('-5 secs');
```

so it's in the past and I can be sure the next timestamp is good for comparison.

**Pull request merged**
