### PR TITLE
PSR-7 compatibility docs

### PR DESCRIPTION
**Pull request by ojhaujjwal**
Not enough docs but something is better than nothing.

### CODE REVIEW

**Comment by bakura10** [comment]
Can you check why travis is failing?

**Comment by ojhaujjwal** [comment]
1) ZfrOAuth2Test\Server\Grant\AuthorizationGrantTest::testCanCreateTokenResponse with data set #0 (true)
Failed asserting that 3599 matches expected 3600.

**Comment by bakura10** [comment]
Ha I see... I'll need to find a better way for this test as it can randomly fails.

**Comment by ojhaujjwal** [comment]
I agree.

**Pull request merged**
